### ISSUE TITLE
RNA: Regular featureCounts module parses biotype log

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC_NGI#14]
There are two featureCounts summary files from the RNA seq pipeline, MultiQC seems to randomly parse one or the other, depending on which it finds first.

A config option should specifically ignore these files:

```yaml
fn_ignore_files:
  - '*biotype.featureCounts.txt.summary'
```

While I'm at it, create a standalone NGI config file which is loaded by the plugin. Do this instead of the current manual setup with Isak.

**Comment by ewels** [comment]
Can't just ignore these files, as we need to parse them in the NGI biotype module. Instead, modify the featureCounts search pattern so that it doesn't pick them up:

```yaml
sp:
  featureCounts:
    fn: '*_gene.featureCounts.txt.summary'
  featureCounts_biotype:
    fn: '*_biotype.featureCounts.txt.summary'
```
